
[window]

opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark" # "Dark"

[font]
size = 12.0
# normal.family = "Cascadia Code PL"
# bold.family = "Cascadia Code PL"
# italic.family = "Cascadia Code PL"
# bold_italic.family = "Cascadia Code PL"

